package VEW.XMLCompiler.ASTNodes;

public enum UnaryPrimitive {
	ABS, ACOS, ASIN, ATAN, COS, EXP, LN, LOGTEN, RND, SIN,
	SQRT, TAN, DENSITYAT, DEPTHFORFI, DEPTHFORVI, FULLIRRADAT,
	SALINITYAT, TEMPAT, UVIRRADAT, INTEGRATE
}
